// <auto-generated />
using System;
using Demo_API_StudentClass.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Demo_API_StudentClass.Migrations
{
    [DbContext(typeof(DbWebAPIContext))]
    partial class DbWebAPIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Demo_API_StudentClass.Data.Models.Student", b =>
                {
                    b.Property<int>("IdStudent")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("State")
                        .HasColumnType("bit");

                    b.Property<DateTime>("birth")
                        .HasColumnType("datetime2");

                    b.HasKey("IdStudent");

                    b.ToTable("Student", (string)null);
                });

            modelBuilder.Entity("Demo_API_StudentClass.Data.Models.StudentClass", b =>
                {
                    b.Property<int>("IdStudent")
                        .HasColumnType("int");

                    b.Property<int>("IdClass")
                        .HasColumnType("int");

                    b.Property<bool>("State")
                        .HasColumnType("bit");

                    b.HasKey("IdStudent", "IdClass");

                    b.HasIndex("IdClass");

                    b.ToTable("StudentClass", (string)null);
                });

            modelBuilder.Entity("Demo_API_StudentClass.Models.Class", b =>
                {
                    b.Property<int>("IdClass")
                        .HasColumnType("int");

                    b.Property<string>("Classroom")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("NameClass")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<bool>("State")
                        .HasColumnType("bit");

                    b.HasKey("IdClass");

                    b.ToTable("Class", (string)null);
                });

            modelBuilder.Entity("Demo_API_StudentClass.Data.Models.StudentClass", b =>
                {
                    b.HasOne("Demo_API_StudentClass.Models.Class", "Class")
                        .WithMany("StudentsClasses")
                        .HasForeignKey("IdClass")
                        .IsRequired();

                    b.HasOne("Demo_API_StudentClass.Data.Models.Student", "Student")
                        .WithMany("StudentClasses")
                        .HasForeignKey("IdStudent")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Demo_API_StudentClass.Data.Models.Student", b =>
                {
                    b.Navigation("StudentClasses");
                });

            modelBuilder.Entity("Demo_API_StudentClass.Models.Class", b =>
                {
                    b.Navigation("StudentsClasses");
                });
#pragma warning restore 612, 618
        }
    }
}
